name: Headless Processing

on:
  push:
    paths:
      - .github/workflows/headless-processing.yml
      - .
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: .

    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: |
            .
      - name: Fetch Processing
        run: curl -L https://github.com/processing/processing4/releases/download/processing-1283-4.0b8/processing-4.0b8-linux-x64.tgz --output processing.tar.gz
      - name: Build
        run: docker build -t ghcr.io/${OWNER,,}/headless-processing:${VERSION} .
        env:
          OWNER: ${{ github.repository_owner }}
          VERSION: ${{ matrix.version }}
      - name: Login
        run: echo $CR_PAT | docker login ghcr.io -u ${OWNER,,} --password-stdin
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
      - name: Push
        run: docker push ghcr.io/${OWNER,,}/headless-processing:${VERSION}
        env:
          OWNER: ${{ github.repository_owner }}
          VERSION: ${{ matrix.version }}